<?php
/**
 * @file
 * A description of what your module does.
 */

include_once dirname(__FILE__) . '/ams_uploader_functions.inc';

// TODO: Fix 'stream_cast is not implemented' warning (PHP 5.4, 5.5).
// TODO: Add admin menu options to add one or many local server names (to test locality of files)
// TODO: Add admin menu options to add 'applications dirs' for RTMP and HTML streams.
// TODO: New categories automatically create pages with all items assigned to that category.
// TODO: Delete Node, Delete File?
// TODO: Implement 'Do Not Manage' checkbox.


function ams_uploader_menu() {
    $items = array();

    $items['admin/config/services/ams_uploader'] = array(
        'title' => t('AMS Uploader Module Settings'),
        'description' => 'Configure FQDN for media streaming server.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ams_uploader_admin_form'),
        'access arguments' => array('administer ams uploader module settings'),
        'file' => 'ams_uploader.admin_form.inc',
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/services/ams_uploader/settings'] = array(
        'title' => t('Settings'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );

    return $items;
}

function ams_uploader_permission() {
    return array(
        'administer ams uploader settings' => array(
            'title' => t('Administer ams uploader configuration'),
            'description' => t('Perform administration tasks on ams uploader module.'),
        ),
    );
}

/**
 * Implements hook_node_access().
 */
function ams_uploader_node_access($node, $op, $account) {
    $type = is_string($node) ? $node : $node->type;
    //If user is viewing media content type and they are not auth user, don't show page
    if ($type == 'media' && $op == 'view' && $node->field_authenticated[$node->language][0]['value'] == 1) {
        if (in_array('anonymous user', $account->roles)) {
            return NODE_ACCESS_DENY;
        }
    }
}

/**
 * Implements hook_formID_alter().
 *
 * @param $form
 * @param $form_state
 * @return mixed
 */
function ams_uploader_form_media_node_form_alter(&$form, &$form_state){

    // For form builder functions, js must be added as such:
    $form['#attached']['js'] = array(
        drupal_get_path('module', 'ams_uploader') . '/scripts/ams_uploader.js',
    );

    array_unshift($form['#validate'], 'ams_uploader_media_node_form_validate');

    $form['title']['#weight'] = -5;
    $form['body']['#weight'] = 1;

    $form['media_group'] = array(
        '#type' => 'fieldset',
        '#title' => t('Media Source:  Add an uploaded file OR an URL (Not Both).'),
        '#weight' => 2,
    );

    $form['media_group']['field_media_upload'] = $form['field_media_upload'];
    $form['media_group']['field_media_url'] = $form['field_media_url'];

    unset($form['field_media_upload']);
    unset($form['field_media_url']);

    $form['field_authenticated']['#weight'] = 3;
    $form['field_directory']['#weight'] = 4;
    $form['field_category']['#weight'] = 5;
    $form['field_tags']['#weight'] = 6;


    return $form;
}


/**
 * Implements hook_form_validate()
 *
 * @param $form
 * @param $form_state
 */
function ams_uploader_media_node_form_validate($form, &$form_state){
    // TODO: detect if uri parses to currently managed file.  If so, error and give link to page.

    $media_url = $form_state['values']['field_media_url']['und'][0]['value'];
    $media_upload = $form_state['values']['field_media_upload']['und'][0]['fid'];

    $has_value_url = isset($media_url) && !($media_url == "");
    $has_value_upload = isset($media_upload) && !($media_upload == 0);

    if (!($has_value_url) && !($has_value_upload)){
        form_set_error('field_media_upload', t("You must either upload a media file OR enter a valid media url."));
        form_set_error('field_media_url');
    }
    if($has_value_url && !(is_http($media_url) || is_rtmp($media_url))){
        form_set_error('field_media_url', t('You have entered an invalid media URL.  It must start with http, https, or rtmp.'));
    }
    if($has_value_url) {
        // Make sure this stream exists
    }

}



/**
 * Implements hook_node_presave().
 */
function ams_uploader_node_presave($node) {

    global $user;
    if ($node->type == 'media') {

        $url_was_submitted = false;
        $url = "";
        // Media was uploaded or media already managed.
        if(isset($node->field_media_upload[$node->language][0]['fid']) && !empty($node->field_media_upload[$node->language][0]['fid'])) {
            $fid = $node->field_media_upload[$node->language][0]['fid'];
            $file = file_load($fid);
            list($filename_no_ext, $ext) = get_filename_and_extension($file->uri);
            $url_was_submitted = false;
        // New node, entered URL.
        } else if (isset($node->field_media_url[$node->language][0]['value'])) {
            $url = $node->field_media_url[$node->language][0]['value'];
            $url_was_submitted = true;
            $is_local_uri = get_local_path_or_false($url);

            if($is_local_uri) {

                // Set up Drupal file object and have drupal manage it from now on.
                list($filename_no_ext, $ext) = get_filename_and_extension($is_local_uri);
                $filename = $filename_no_ext . '.' . $ext;
                $file = new stdClass;
                $file->uid = $user->uid;
                $file->filename = $filename;
                $file->uri = $is_local_uri;
                $finfo = finfo_open(FILEINFO_MIME_TYPE);
                $mime = finfo_file($finfo, $is_local_uri);
                finfo_close($finfo);
                $file->filemime = $mime;
                $file->filesize = filesize($is_local_uri);
                $file->status = 1;
                file_save($file);

                $type = 'streaming media file';
                $id = $file->fid;
                file_usage_add($file, 'ams_uploader', $type, $id);

                $node->field_media_upload[$node->language][0]['fid'] = $file->fid;
                $node->field_media_upload[$node->language][0]['display'] = 1;

                if ($file === FAlSE) {
                    return;
                }
            }
            else {
                // Not a local URL, Nothing to be done. Create video node using existing url.
                return;
            }

        } else {
            form_set_error('title', t('Neither URL nor Media upload is set.  This doesnt make sense.'));
            return;
        }

        if($file){
            $filename = $file->filename;
        } else {
            return;

        }

        $authenticated = !($node->field_authenticated[$node->language][0]['value'] == 0);
        $appName = $authenticated ? 'unm' : 'vod';
        // Get $subDir
        if($url_was_submitted) {
            // If the URL was submitted, we will infer the subdirectory structure from the URL itself.
            list($inferred_original_app_name, $path_tail) = get_app_name_and_path_tail_from_url($url);
            // Make sure that delimiter looks like a directory so it doesnt false positive on us.
            $delimiter1 = '/' . $inferred_original_app_name . '/';
            $subDir = get_str_between($url, $delimiter1, $filename);
            $node->field_directory[$node->language][0]['value'] = $subDir;
        }
        else {
            // If a media upload was processed, or this is an edit of a currently managed file,
            // the user is free to enter their own preferred sub directory structure.  We will also
            // attempt to clean up any undesired slashes to keep things formatted like we want them.
            $subDir = empty($node->field_directory[$node->language][0]) ? '' : $node->field_directory[$node->language][0]['value'];
            $subDir = strip_outer_slashes($subDir);
        }


        // Returns path to directory file will be placed in.
        $newpath = get_new_path($appName, $subDir);


        if (!empty($subDir) && !file_prepare_directory($newpath, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
            throw new Exception('Error saving node: Cannot create new directory.');
        }

        //Complete path with filename
        $newpath = $newpath . '/' . $filename;

        //Only move file if a new location has been designated
        if ($file->uri != $newpath) {
            $file = file_move($file, $newpath, FILE_EXISTS_ERROR);
            // TODO: deal with file-copy collisions more elegantly.  Currently errors and dies.  Would like error and continue.
            if ($file === FALSE) {
                throw new Exception('Could not copy file to ' . $newpath . '. Make sure the file doesnt already exist, or check permissions.');
            }
        }

        //Set rtmp url to text field
        $node->field_media_url[$node->language][0]['value'] = generate_url($filename_no_ext, $ext, $subDir, $appName);

    }
}

/**
 * Implements hook_field_formatter_info().
 */
function ams_uploader_field_formatter_info() {
    return array(
        'ams_formatter' => array(
            'label' => 'AMS Player',
            'description' => 'Flash player to embed videos/audo from Adobe Media Server',
            'field types' => array('text'),
            'settings' => array( //Array of the settings we'll create
                'video_width' => '640', //default value for width
                'video_height' => '480', //default for height
            ),
        )
    );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function ams_uploader_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
    //This gets the view_mode where our settings are stored
    $display = $instance['display'][$view_mode];
    //This gets the actual settings
    $settings = $display['settings'];
    //Initialize the element variable
    $element = array();
    //Add your select box
    $element['video_width'] = array(
        '#type' => 'text',
        '#title' => t('Video Width'),
        '#description' => t('Set the width of the video (pixels)'),
        '#default_value' => $settings['video_width'],
    );
    $element['video_height'] = array(
        '#type' => 'text',
        '#title' => t('Video Height'),
        '#description' => t('Set the height of the video (pixels)'),
        '#default_value' => $settings['video_height'],
    );
    return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function ams_uploader_field_formatter_settings_summary($field, $instance, $view_mode) {
    $display = $instance['display'][$view_mode];
    $settings = $display['settings'];
    $summary = t('Use width @widthpx and height @heightpx ', array(
        '@width' => $settings['video_width'],
        '@height' => $settings['video_height'],
    )); // we use t() for translation and placeholders to guard against attacks
    return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function ams_uploader_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    $element = array(); // Initialize the var
    $mod_path = drupal_get_path('module', 'ams_uploader');
    $settings = $display['settings']; // get the settings
    $width = $settings['video_width'];
    $height = $settings['video_height'];

    $player = base_path() . $mod_path . '/swfs/StrobeMediaPlayback.swf';

    // Create the object code
    foreach ($items as $delta => $item) {
        $url = $item['safe_value']; // Getting the actual value
        //Generate object code with player and url embedded
        $embedCode = '
    <object type="application/x-shockwave-flash" data="' . $player . '"
      width="' . $width . '" height="' . $height . '">
      <param name="quality" value="high">
      <param name="bgcolor" value="#000000">
      <param name="allowscriptaccess" value="sameDomain">
      <param name="allowfullscreen" value="true">
      <param name="wmode" value="direct">
      <param name="flashvars" value="src=' . $url . '">
    </object>
    ';
    }
    if (isset($embedCode)) {
        $element[0]['#markup'] = $embedCode; // Assign it to the #markup of the element
    }
    return $element;
}


/**
 * Custom Stream Wrapper for AMS application area
 */
/**
 * Implements hook_stream_wrappers().
 */
function ams_uploader_stream_wrappers() {
    return array(
        'ams' => array(
            'name' => t('AMS Application media files'),
            'class' => 'AMSStreamWrapper',
            'description' => t('Adobe Media server base directory for streaming purposes.'),
            'type' => STREAM_WRAPPERS_LOCAL_HIDDEN,
        ),
    );
}

/**
 * Default files (ams://) stream wrapper class.
 */
class AMSStreamWrapper extends DrupalPublicStreamWrapper {
    public function getDirectoryPath() {
        $result = db_query('SELECT * FROM ams_uploader_ams_root');
        $count = $result->rowCount();

        if(isset($result) && !(empty($result)) && $count == 1){
            foreach ($result as $row) {
                $path = $row->path;
            }
        }
        else {
            throw new Exception("AMSStreamWrapper: Trying to map to ams installation root.  DB query returned " . $count . " rows, expected 1.");
        }
        return $path;
    }
}